### ISSUE TITLE
[Bug]: anic: utf8 name validation requested but model.NameValidationScheme is not set to UTF8

### ISSUE THREAD

**Issue by east4ming** [k8sgpt-ai/k8sgpt#1361]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [X] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.48

### Kubernetes Version

v1.30.6

### Host OS and its Version

Ubuntu 24.04

### Steps to reproduce

1. `k8sgpt integrations activate prometheus -n monitoring-system`
2. `k8sgpt analyze --filter PrometheusConfigValidate --namespace monitoring-system --explain`

```logs
$ k8sgpt analyze --filter PrometheusConfigValidate --namespace monitoring-system --explain
panic: utf8 name validation requested but model.NameValidationScheme is not set to UTF8 [recovered]
	panic: utf8 name validation requested but model.NameValidationScheme is not set to UTF8

goroutine 97 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc001096c68)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x6d
panic({0x39318c0?, 0x4f44d30?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate(0xc000e1f188, {0x6fc23ac00, 0x2540be400, {0x7a51220, 0x4, 0x4}, 0x6fc23ac00, 0x0, {0x0, 0x0}, ...})
	/home/runner/go/pkg/mod/github.com/prometheus/prometheus@v0.300.1/config/config.go:836 +0x42c
github.com/prometheus/prometheus/config.(*Config).UnmarshalYAML(0xc000812588, 0x7fffb12cb110?)
	/home/runner/go/pkg/mod/github.com/prometheus/prometheus@v0.300.1/config/config.go:397 +0x4c7
gopkg.in/yaml%2ev2.(*decoder).callUnmarshaler(0xc000e132c0, 0xc000eb0ee0, {0x7fffb12cb110, 0xc000812588})
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/decode.go:270 +0x94
gopkg.in/yaml%2ev2.(*decoder).prepare(0xc000e132c0, 0xc000eb0ee0, {0x42d0480?, 0xc000812588?, 0xc000618268?})
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/decode.go:313 +0x256
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000e132c0, 0xc000eb0ee0, {0x42d0480?, 0xc000812588?, 0x13e96cb?})
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/decode.go:364 +0x13b
gopkg.in/yaml%2ev2.(*decoder).document(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/decode.go:384
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0x3d91f00?, 0xc000812588?, {0x42d0480?, 0xc000812588?, 0x0?})
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/decode.go:360 +0x110
gopkg.in/yaml%2ev2.unmarshal({0xc001178000, 0x16b62, 0x18000}, {0x3d91f00, 0xc000812588}, 0x0)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:148 +0x376
gopkg.in/yaml%2ev2.Unmarshal(...)
	/home/runner/go/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:81
github.com/k8sgpt-ai/k8sgpt/pkg/integration/prometheus.unmarshalPromConfigBytes({0xc0005a1600, 0xc92, 0xc93})
	/home/runner/work/k8sgpt/k8sgpt/pkg/integration/prometheus/config_analyzer.go:282 +0x165
github.com/k8sgpt-ai/k8sgpt/pkg/integration/prometheus.(*ConfigAnalyzer).Analyze(0xc000c94000?, {0xc000e80c90, {0x4f9efd8, 0x7a97540}, {0x7fffffff8ea9, 0x11}, {0x0, 0x0}, {0x4f9f0b8, 0x7a46e20}, ...})
	/home/runner/work/k8sgpt/k8sgpt/pkg/integration/prometheus/config_analyzer.go:64 +0x145
github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).executeAnalyzer(0xc000288960, {0x4f4f3e0?, 0x7a97540?}, {0xc001778930, 0x18}, {0xc000e80c90, {0x4f9efd8, 0x7a97540}, {0x7fffffff8ea9, 0x11}, ...}, ...)
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:297 +0x118
created by github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis in goroutine 1
	/home/runner/work/k8sgpt/k8sgpt/pkg/analysis/analysis.go:265 +0x565
```

### Expected behaviour

Fix it

**Comment by yankay** [comment]
It seems fixed by https://github.com/prometheus/common/pull/724

**Comment by modevops** [comment]
I think this is still an issue.  I installed the latest version of prometheus version helm chart kube-stack-prometheus 69.7.4
I am evaluating k8sgpt for are eks cluster and if  prometheus is not working it take huge use case for k8sgpt out of the picture.  This needs to be fixed.  I need the 3.0 version because I also use datadog.  It would be good to have guidance on versions supported.

Looking at the documentation I have the prometheus setting right
https://prometheus.io/docs/guides/utf8/
https://github.com/prometheus-community/helm-charts/pull/5397
``
prometheus info
prometheus % kubectl get  prometheuses -n monitoring -o yaml
    image: quay.io/prometheus/prometheus:v3.2.1
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    nameValidationScheme: Legacy
``
`` 
k8sgpt analyze --filter PrometheusConfigRelabelReport -n monitoring --explain
panic: utf8 name validation requested but model.NameValidationScheme is not set to UTF8 [recovered]
	panic: utf8 name validation requested but model.NameValidationScheme is not set to UTF8

goroutine 137 [running]:
gopkg.in/yaml%2ev2.handleErr(0x140022e4c18)
	gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x7c
panic({0x1088ae840?, 0x109495970?})
	runtime/panic.go:787 +0x124
github.com/prometheus/prometheus/config.(*ScrapeConfig).Validate(0x1400214a788, {0x6fc23ac00, 0x2540be400, {0x10c290020, 0x4, 0x4}, 0x6fc23ac00, 0x0, {0x0, 0x0}, ...})
	github.com/prometheus/prometheus@v0.300.1/config/config.go:836 +0x3c8
github.com/prometheus/prometheus/config.(*Config).UnmarshalYAML(0x14000871608, 0x113ec47c8?)
	github.com/prometheus/prometheus@v0.300.1/config/config.go:397 +0x3fc
gopkg.in/yaml%2ev2.(*decoder).callUnmarshaler(0x1400216f1a0, 0x14000665110, {0x113ec47c8, 0x14000871608})
	gopkg.in/yaml.v2@v2.4.0/decode.go:270 +0x98
gopkg.in/yaml%2ev2.(*decoder).prepare(0x1400216f1a0, 0x14000665110, {0x109363520?, 0x14000871608?, 0x14002328308?})
	gopkg.in/yaml.v2@v2.4.0/decode.go:313 +0x258
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0x1400216f1a0, 0x14000665110, {0x109363520?, 0x14000871608?, 0x14002328308?})
	gopkg.in/yaml.v2@v2.4.0/decode.go:364 +0x150
gopkg.in/yaml%2ev2.(*decoder).document(...)
	gopkg.in/yaml.v2@v2.4.0/decode.go:384
gopkg.in/yaml%2ev2.(*decoder).unmarshal(0x108e173c0?, 0x14000871608?, {0x109363520?, 0x14000871608?, 0x14001a728a0?})
	gopkg.in/yaml.v2@v2.4.0/decode.go:360 +0x124
gopkg.in/yaml%2ev2.unmarshal({0x140023c8000, 0x9b04, 0xa000}, {0x108e173c0, 0x14000871608}, 0x0)
	gopkg.in/yaml.v2@v2.4.0/yaml.go:148 +0x30c
gopkg.in/yaml%2ev2.Unmarshal(...)
	gopkg.in/yaml.v2@v2.4.0/yaml.go:81
github.com/k8sgpt-ai/k8sgpt/pkg/integration/prometheus.unmarshalPromConfigBytes({0x140001f9200, 0x822, 0x822})
	github.com/k8sgpt-ai/k8sgpt/pkg/integration/prometheus/config_analyzer.go:282 +0x144
github.com/k8sgpt-ai/k8sgpt/pkg/integration/prometheus.(*RelabelAnalyzer).Analyze(0x10c2dcd28?, {0x14001a4d0b0, {0x1094fe198, 0x10c2dcd28}, {0x16b6978f9, 0xa}, {0x0, 0x0}, {0x1094fe278, 0x10c2855a0}, ...})
	github.com/k8sgpt-ai/k8sgpt/pkg/integration/prometheus/relabel_analyzer.go:34 +0x140
github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).executeAnalyzer(0x14002c963c0, {0x1094aadc0?, 0x10c2dcd28?}, {0x14001a9a2e0, 0x1d}, {0x14001a4d0b0, {0x1094fe198, 0x10c2dcd28}, {0x16b6978f9, 0xa}, ...}, ...)
	github.com/k8sgpt-ai/k8sgpt/pkg/analysis/analysis.go:297 +0xf8
created by github.com/k8sgpt-ai/k8sgpt/pkg/analysis.(*Analysis).RunAnalysis in goroutine 1
	github.com/k8sgpt-ai/k8sgpt/pkg/analysis/analysis.go:265 +0x400
``

**Comment by modevops** [comment]
any update on this?   I was using the latest version of k8sgpt cli, on eks cluster had latest version of k8sgpt operator, and latest helm chart of kube-prometheus-stack.  I would really like this fixed.

**Comment by yankay** [comment]
It seems just pending the Prometheus release next version :-)

**Comment by AlexsJones** [comment]
Fixed in https://github.com/k8sgpt-ai/k8sgpt/pull/1412 Thanks team
